"""InferBackend protocol — unified interface for all inference backends."""

from __future__ import annotations

from typing import Protocol

import numpy as np


class InferBackend(Protocol):
    n_action_steps: int

    def start(self) -> None: ...
    def stop(self) -> None: ...
    def reset(self) -> None: ...
    def notify_obs(self, obs: dict) -> None: ...
    def get_action(self) -> np.ndarray | None: ...
    def qsize(self) -> int: ...

    @property
    def failed(self) -> bool: ...
